export const REQUEST_TODOS = 'REQUEST_TODOS';
export const RECIEVE_TODOS = 'RECIEVE_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE';
export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST';
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const TOGGLE_TODO_SUCCESS = 'TOGGLE_TODO_SUCCESS';
